scan:
  _target_: holopipe.scan.P05Scan
  name: t
  energy: 17.0
  holder: 220
  z01: 190
  z02: 19826.473541018642
  tasks:
    - flatfield
    - find_focus
    - reconstruction
    - tomography
  px_size: 0.0065
  z01_confidence: 10
  detector: Hamamatsu
  data:
    total_size:
      - 2048
      - 2048
    fov_size:
      - 2048
      - 2048
    window_type: blackman