[build-system]
requires = ["setuptools >= 72.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}

[project]
name="holowizard"
version = "1.0.7"
requires-python = ">=3.11,<=4.0"
readme = "README.md"
license = {file="LICENSE"}
keywords = ["phase retrieval", "near-field holography", "ASRM"]
authors = [
  {name = "Johannes Dora", email = "johannes.dora@desy.de"},
  {name = "Johannes Hagemann", email = "johannes.hagemann@desy.de"},
  {name = "Silja Flenner", email="silja.flenner@hereon.de"},
]
classifiers = [
  "Programming Language :: Python"
]

maintainers = [
  {name = "Johannes Dora", email = "johannes.dora@desy.de"},
  {name = "André Lopes", email="andre.lopes@hereon.de"}
]

[project.urls]
Repository = "https://gitlab.desy.de/fs-petra/software/holowizard/"
Livereco = "https://gitlab.desy.de/fs-petra/software/livereco_server/"
Livereco_Interface = "https://gitlab.desy.de/fs-petra/software/livereco_interface"
HoloForge = "https://gitlab.desy.de/fs-petra/software/holography-data-ml"
HoloPipe = "https://gitlab.desy.de/fs-petra/software/holopipe"

[project.optional-dependencies]
all=["holowizard[livereco]","holowizard[livereco_interface]","holowizard[holoforge]"]
livereco=["livereco==1.4.5","holowizard[livereco_interface]"]
livereco_interface=["livereco_interface==1.0.21"]
holoforge=["holoforge==1.0.8"]
holopipe=["holopipe==1.0.6","holowizard[livereco]","holowizard[livereco_interface]"]




